on:
  push:
    branches:
      - 'leet-build*'

name: Multi Platform Builder
jobs:
  build:
    name: Building Binaries
    strategy:
      matrix:
#        platform: [windows-latest]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
#        toolchain: stable
        toolchain: nightly-2020-06-10
        components: rustfmt
#        target: ${{ matrix.target }}
        override: true
    # Install OS specific dependencies
    - name: Install Linux dependencies
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update && \
        sudo apt-get -y install \
          openssl \
          libssl-dev \
          pkg-config \
          libsqlite3-dev \
          git \
          cmake \
          libc++-dev \
          libc++abi-dev \
          libprotobuf-dev \
          protobuf-compiler
    - name: Install macOS dependencies
      if: matrix.platform == 'macOS-latest'
      run: brew install cmake
    - name: Install Windows dependencies
      if: matrix.platform == 'windows-latest'
      run: |
        choco install tor bzip2
        vcpkg.exe install sqlite3:x64-windows zlib:x64-windows
        vcpkg.exe integrate install
    - name: Build binaries - Nix
      continue-on-error: true  # WARNING: only for this example, remove it!
      if: matrix.platform != 'windows-latest'
      uses: actions-rs/cargo@v1
      env:
        CC: gcc
      with:
        command: build
        args: --release --verbose
    - name: Build binaries - Windows
      continue-on-error: true  # WARNING: only for this example, remove it!
      if: matrix.platform == 'windows-latest'
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --verbose
    - name: Debug Helper
      continue-on-error: true  # WARNING: only for this example, remove it!
      shell: bash
      run: |
        ls -la '${{ github.workspace }}'
        ls -la '${{ github.workspace }}/target/release/'
#        ls -la "${{ github.workspace }}/target/release/"{tari_base_node,tari_base_node.exe}
    - name: Upload Windows binary
      if: matrix.platform == 'windows-latest'
      uses: actions/upload-artifact@v2
      with:
        name: tari_base_node - release - ${{ matrix.platform }}
        path: '${{ github.workspace }}/target/release/tari_base_node.exe'
    - name: Upload Nix binary
      if: matrix.platform != 'windows-latest'
      uses: actions/upload-artifact@v2
      with:
        name: tari_base_node - release - ${{ matrix.platform }}
        path: '${{ github.workspace }}/target/release/tari_base_node'
