name: Multi Platform Builder

on:
  push:
    branches:
      - 'leet-build*'

env:
  target_cpu: "x86-64"
  RUSTFLAGS: "-C target_cpu=x86-64"
  features: "safe"
#  TBN_FILENAME: 'tari_base_node'
#  SQLITE3_LIB_DIR: 'C:\vcpkg\installed\x64-windows\lib'
#  VCPKGRS_DYNAMIC: 1
#  SQLITE_STATIC: 1
#  SQLITE3_STATIC: 1

jobs:
  build:
    name: Building Binaries
    strategy:
      matrix:
#        os: [windows-latest]
#        os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-18.04, macos-10.15, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
#        toolchain: stable
        toolchain: nightly-2020-06-10
        components: rustfmt
#        target: ${{ matrix.target }}
        override: true

    - name: Install Ubuntu dependencies
      if: startsWith(matrix.os,'ubuntu')
      run: |
        sudo apt-get update && \
        sudo apt-get -y install \
          openssl \
          libssl-dev \
          pkg-config \
          libsqlite3-dev \
          git \
          cmake \
          zip \
          libc++-dev \
          libc++abi-dev \
          libprotobuf-dev \
          protobuf-compiler
    - name: Install macOS dependencies
      if: startsWith(matrix.os,'macos')
      run: brew install cmake zip
    - name: Install Windows dependencies
      if: startsWith(matrix.os,'windows')
      run: |
        vcpkg.exe install sqlite3:x64-windows zlib:x64-windows
        choco upgrade llvm zip psutils -y

    - name: set environment variables - Nix
      if: "!startsWith(matrix.os,'Windows')"
      uses: allenevans/set-env@v1.0.0
      with:
        overwrite: true
        CC: gcc
        TBN_FILENAME: 'tari_base_node'
        SHARUN: 'shasum -a 256'
    - name: set environment variables - Windows
      if: startsWith(matrix.os,'Windows')
      uses: allenevans/set-env@v1.0.0
      with:
        overwrite: true
        SQLITE3_LIB_DIR: 'C:\vcpkg\installed\x64-windows\lib'
        TBN_FILENAME: 'tari_base_node.exe'
        SHARUN: 'pwsh C:\ProgramData\chocolatey\lib\psutils\tools\psutils-master\shasum.ps1 -a 256'
#        RUSTFLAGS: '-Ctarget-feature=+crt-static'
#        CC: gcc

    - name: Build binaries
      continue-on-error: true  # WARNING: only for this example, remove it!
      shell: bash
      run: |
        cd applications/tari_base_node
        cargo build --release --bin tari_base_node --features $features

    - name: Prep binaries
      continue-on-error: true  # WARNING: only for this example, remove it!
      shell: bash
      run: |
        mkdir -p "$GITHUB_WORKSPACE/binaries/${{ matrix.os }}"
        cd "$GITHUB_WORKSPACE/binaries/${{ matrix.os }}"
        VERSION=$(awk -F ' = ' '$1 ~ /version/ { gsub(/[\"]/, "", $2); printf("%s",$2) }' "$GITHUB_WORKSPACE/applications/tari_base_node/Cargo.toml")
        BINFILE="${TBN_FILENAME}-${{ matrix.os }}-${target_cpu}-${features}-${VERSION}"
        echo "Copying file ${BINFILE} too $(pwd)"
        cp -v "$GITHUB_WORKSPACE/target/release/${TBN_FILENAME}" "./${BINFILE}"
        echo "Archive ${BINFILE} too ${BINFILE}.zip"
        zip -j "${BINFILE}.zip" "${BINFILE}"
        echo "Compute shasum"
        ${SHARUN} "${BINFILE}.zip" >> "${BINFILE}.zip.sha256"
        cat "${BINFILE}.zip.sha256"
        echo "Verifications is "
        ${SHARUN} --check "${BINFILE}.zip.sha256"
#        printenv

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.TBN_FILENAME }} - release - ${{ matrix.os }} - ${{ env.target_cpu }} - ${{ env.features }}
        path: '${{ github.workspace }}/target/release/${{ env.TBN_FILENAME }}'
