---
name: Test Results - workflow_call

'on':
  workflow_call:

permissions: {}

jobs:
  publish-results:
    name: Publish Results
    runs-on: ubuntu-latest

    permissions:
      checks: write

      # needed unless run with comment_mode: off
      pull-requests: write

      # required by download step to access artifacts API
      actions: read

    steps:
      - name: Download and Extract Artifacts
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          mkdir -p artifacts
          cd artifacts
          
          artifacts_url=${{ github.event.workflow_run.artifacts_url }}
          
          gh api --paginate "$artifacts_url" -q '.artifacts[] | [.name, .archive_download_url] | @tsv' | while read artifact
          do
            IFS=$'\t' read name url <<< "$artifact"
            gh api $url > "$name.zip"
            unzip -d "$name" "$name.zip"
          done
          ls -alhtR

      - name: Publish Test Report - JUnit
        if: always()
        continue-on-error: true
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: 'artifacts/**/*junit*.xml'

      - name: Publish Test Report - Jest Tests
        if: always()
        continue-on-error: true
        uses: dorny/test-reporter@v1
        with:
          #working-directory: artifacts
          artifact: /test-results-(.*)/
          name: 'JEST Tests $1'
          #name: JEST Tests
          path: '**/*junit*.xml'
          reporter: jest-junit
